# Generated by Django 3.2.12 on 2022-04-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pariente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Pariente',
        ),
    ]
